### ISSUE TITLE
You're ugly

### ISSUE THREAD

**Issue by porkypig101** [evan-goode/almostti.me#1]
![academicbowl2-475x259](https://cloud.githubusercontent.com/assets/7415262/23717233/f7fb2ea0-0400-11e7-8271-035f3c9d0b61.jpg)

**Comment by evan-goode** [comment]
![f7fb2ea0-0400-11e7-8271-035f3c9d0b61](https://cloud.githubusercontent.com/assets/7495216/23728677/18b265ca-042c-11e7-84d2-8f4f50673768.jpg)
